
pipeline {
  agent any

 stages {
    stage('Tests unitaires') {
      steps {
        // Publier systématiquement les tests, envoyer un mail si échec
        echo 'Exécution des tests unitaires'
      }
    }
    
    
    stage('Parallel Stage') {

      parallel {
        stage('Analyse de vulnérabilités') {
          agent any
          steps {  
            echo 'Démarrage plugin OWASP'

          }
        }
        stage('Qualité') {
          agent any
          steps {  
            // Start an analysis
            echo 'Démarrage Analyse Sonar '
          }
        }
      }
    }
    stage("Quality Gate") {
      steps {
	  // attendre le résultat de l'analyse 
    	echo 'Watch quality gate'       
       }
    }
    stage("Nexus snapshot-deployement") {
      steps {
          // Déploiement Nexus
        echo 'Déploiement snapshot'
       }
    }
    stage('Release') {
    /* Execution seulement sur master */
      agent none     
      steps {
	// Faire une release
        echo 'Release'
      }
    }
    stage('Déploiement sur DataCenter') {
	/* Execution seulement sur master */
      agent none     
      steps {
	
        echo 'Déploiement sur un data center'
      }
    }

 }           
}
 
